### ISSUE TITLE
Customise commit message & body

### ISSUE THREAD

**Issue by mikestreety** [axllent/gitlabci-composer-update-mr#8]
Hey,

Thanks (again) for a fantastic & useful bit of code!

Would it be possible to configure the commit message? Internally, we have a convention of something like the following - would be _amazing_ if this could follow suit

```
Dep: Update composer dependencies

deployer/deployer: v7.1.4...v7.2.0
```

Basically spitting out what you put in the MR body into the commit body.

Thanks again!

**Comment by axllent** [comment]
I love this idea, far nicer than `$ composer update`. This is definitely possible, although I'm a little conflicted by the `Dep: Update composer dependencies` as this seems very personal to your team, someone else may want something else. I think I have a solution though, the ability to overwrite the commit message "title" using a command-line flag (it will include the list of updated packages either way). Working on a solution now... :)

**Comment by mikestreety** [comment]
Thanks for the quick response!

100% that it a personal commit message - but a way to customise the title would be great (as well as the option to include the updates in the body). Happy to add more CI variables 👍

**Comment by axllent** [comment]
No problem, I'm glad others find it useful too!

I have just added this feature (documented in the README) as either an environment variable `COMPOSER_MR_COMMIT_TITLE` (Gitlab project settings) or a command-line flag `-t "<commit title>"`. By default the commit message now says "Update composer dependencies", but you can easily change it to whatever you like. All commit messages will include the list of changed packages beneath that too (hardcoded). 

The images will be building shortly and should be finished in the next 15 minutes or so :)

Please let me know if this works for you?

**Comment by mikestreety** [comment]
Incredible work, thank you!

![image](https://user-images.githubusercontent.com/354085/221171904-73ec3d45-6f87-49ea-80de-7f5a5a806ceb.png)

**Comment by axllent** [comment]
Awesome, glad to help!
